name: jumpbox

stemcells:
  - alias:   default
    os:      ubuntu-xenial
    version: latest

releases:
  - name:    containers
    version: latest

update:
  canaries:          1
  max_in_flight:     1
  serial:            true
  canary_watch_time: 1000-120000
  update_watch_time: 1000-120000

instance_groups:
  - name: docker
    instances: 1 
    azs: [z1]
    vm_type: default
    stemcell: default
    networks:
      - name: default
    jobs:
      - name: docker
        release: containers

      - name: jumpbox
        release: containers
        properties:
          users:

            # Candace and Delilah work on the front-end team.
            #
            - username: candace
              group:    front-end
              key:      ssh-ed25519 AAAA....etc....

            - username: delilah
              group:    front-end
              key:      ssh-ed25519 AAAA....etc....

            # Erin, Francine, and Gertrude work on API stuff.
            - username: erin
              group:    api
              key:      ssh-ed25519 AAAA....etc....

            - username: francine
              group:    api
              key:      ssh-ed25519 AAAA....etc....

            - username: gertrude
              group:    api
              key:      ssh-ed25519 AAAA....etc....
