name: jumpbox

stemcells:
  - alias:   default
    os:      ubuntu-xenial
    version: latest

releases:
  - name:    containers
    version: latest

update:
  canaries:          1
  max_in_flight:     1
  serial:            true
  canary_watch_time: 1000-120000
  update_watch_time: 1000-120000

instance_groups:
  - name: docker
    instances: 1 
    azs: [z1]
    vm_type: default
    stemcell: default
    networks:
      - name: default
    jobs:
      - name: docker
        release: containers

      - name: jumpbox
        release: containers
        properties:
          users:
            - username: jhunt
              key:      ssh-ed25519 AAAA....etc....

          volumes:
            - name: shared
              group: staff

          default:
            group: staff
            mounts:
              - volume: shared
                mountpoint: /shared

              - tmpfs: yes
                mountpoint: /scratch

              - filesystem: /var/vcap/
                mountpoint: /vcap
                options: ro
