---
name: redis

stemcells:
  - alias:   default
    os:      ubuntu-xenial
    version: latest

releases:
  - name:    containers
    version: latest

update:
  canaries:          1
  max_in_flight:     1
  serial:            true
  canary_watch_time: 1000-120000
  update_watch_time: 1000-120000

instance_groups:
  - name: docker
    instances: 1
    azs: [z1]
    vm_type: default
    stemcell: default
    networks:
      - name: default
    persistent_disk: 8192

    jobs:
      - name: docker
        release: containers
        properties:
          recipe:
            version: '3'
            services:
              redis:
                image: redis
                ports: ['6379:6379']
                command: ['redis-server', '--appendonly', 'yes']
                volumes:
                  - 'redis-data:/data'
            volumes:
              redis-data: ~
