---
meta:
  name:    containers
  release: Containers BOSH Release
  target:  pipes
  url:     https://pipes.starkandwayne.com

  exposed: true

  initial_version: 1.1.0

  manifest:
    path: manifests/shield.yml

  git:
    email: ci@starkandwayne.com
    name:  Stark & Wayne CI Bot

  bosh-lite:
    target:   https://10.128.4.73:25555
    username: ((thunder-dome.username))
    password: ((thunder-dome.password))
    cacert:   ((thunder-dome.ca-certificate))

  aws:
    access_key: ((cfcommunity.access))
    secret_key: ((cfcommunity.secret))

  github:
    owner:  cloudfoundry-community
    repo:   containers-boshrelease
    branch: master
    private_key:  ((github.private-key))
    access_token: ((github.access-token))


  shout:
    url:      http://10.128.4.65:7109
    username: ((shout.username))
    password: ((shout.password))
